[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
explicit_package_bases = true
ignore_missing_imports = true
check_untyped_defs = true
mypy_path = "src/types:.venv/lib/python3.12/site-packages"
plugins = "numpy.typing.mypy_plugin"

[tool.mypy-applications]
ignore_missing_imports = false

[tool.mypy-common]
ignore_missing_imports = false
check_untyped_defs = true

[tool.black]
target-version = ['py312']
preview = true

[tool.isort]
profile = "black"
order_by_type = false
combine_as_imports = true
case_sensitive = false
skip_magic_trailing_comma = true
force_sort_within_sections = false

[tool.pyright]
# verboseOutput = true
pythonVersion = "3.12"
extraPaths = [".venv/lib/python3.12/site-packages"]
reportUnusedImport = "error"
reportUnusedClass = "error"
reportUnusedFunction = "error"
reportUnusedVariable = "error"

[tool.ruff]
target-version = "py312"
line-length = 100
indent-width = 4
preview = true

[tool.ruff.lint]
fixable = ["ALL"]
select = [
  # PRAGMA: F401 is for unused imports, you may want to remove this when developing so you can comment/uncomment code.
  "F401",
  "W292",
  "W293",
  "W191",
  "E101",
  "E112",
  "E117",
  "I002",
  "UP035",
]
# To add, when supported by ruff: "W503", "E203"
# see: https://github.com/astral-sh/ruff/issues/2402

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[tool.ruff.lint.isort]
force-sort-within-sections = false
case-sensitive = false
combine-as-imports = true
force-wrap-aliases = true
order-by-type = false


[tool.ruff.format]
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
quote-style = "double"

[tool.pytest.ini_options]
minversion = "7.4"
addopts = "-rP -vv -s --color=yes --capture=tee-sys"
testpaths = ["imfs"]
python_files = ["*_test.py", "test_*.py"]
python_classes = ["test_", "_test", "Test*"]
python_functions = ["test_", "_test"]
